INF QcomPkg/XBLCore/XBLCore.inf

FILE FREEFORM = DDE58710-41CD-4306-DBFB-3FA90BB1D2DD {
    SECTION UI = "uefiplat.cfg"
    SECTION RAW = RawFiles/uefiplat.cfg
}

INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
INF QcomPkg/Drivers/SecRSADxe/SecRSADxe.inf
INF QcomPkg/Drivers/ASN1X509Dxe/ASN1X509Dxe.inf
INF QcomPkg/Drivers/TzDxe/ScmDxeLA.inf
INF QcomPkg/Drivers/TzDxe/TzDxeLA.inf
INF QcomPkg/Drivers/VerifiedBootDxe/VerifiedBootDxe.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/RscRtDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/SCHandlerRtDxe.inf
INF QcomPkg/Drivers/VariableDxe/VariableDxe.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF QcomPkg/Drivers/ResetRuntimeDxe/ResetRuntimeDxe.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF QcomPkg/Drivers/FontDxe/FontDxe.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF QcomPkg/Drivers/QcomMpmTimerDxe/QcomMpmTimerDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF MdeModulePkg/Universal/Disk/PartitionDxe/PartitionDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/VcsDxe/VcsDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe.inf
INF QcomPkg/Drivers/UFSDxe/UFSDxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF QcomPkg/Drivers/MinidumpTADxe/MinidumpTADxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/ButtonsDxe/ButtonsDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeLa.inf
INF QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
INF QcomPkg/Drivers/QcomChargerDxe/QcomChargerDxeLA.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
INF QcomPkg/Drivers/AdcDxe/AdcDxe.inf
INF QcomPkg/Drivers/OcdtDxe/OppoProject.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/HashDxe/HashDxe.inf
INF QcomPkg/Drivers/CipherDxe/CipherDxe.inf
INF QcomPkg/Drivers/MacDxe/MacDxe.inf
INF QcomPkg/SocPkg/KamortaPkg/Drivers/RNGDxe/RngDxe.inf
INF QcomPkg/Drivers/PhoenixDxe/PhoenixDxe.inf
INF QcomPkg/Drivers/QcomBds/QcomBds.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Application/QcomChargerApp/QcomChargerApp.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxeLA.inf

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
    SECTION UI = "BDS_Menu.cfg"
    SECTION RAW = RawFiles/BDS_Menu.cfg
}


FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
    SECTION UI = "logo1.bmp"
    SECTION RAW = RawFiles/logo1.bmp
}


FILE FREEFORM = 02E0AF91-5D44-424F-828F-211ADC520B0C {
    SECTION UI = "Panel_truly_td4330_v2_fhd_cmd.xml"
    SECTION RAW = RawFiles/Panel_truly_td4330_v2_fhd_cmd.xml
}


FILE FREEFORM = 9BAE75D9-A217-4B31-9DCD-00D2609BC6AE {
    SECTION UI = "Panel_truly_td4330_v2_fhd_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_td4330_v2_fhd_vid.xml
}


FILE FREEFORM = 9BAE75D9-A217-4B31-9DCD-00D2609B6784 {
    SECTION UI = "Panel_truly_nt36525_hd_plus_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_nt36525_hd_plus_vid.xml
}


FILE FREEFORM = 00FAA3EC-F837-4068-AE95-68614695C001 {
    SECTION UI = "Panel_oplus20241_s6e8fc1_samsung_fhd_vid.xml"
    SECTION RAW = RawFiles/Panel_oplus20241_s6e8fc1_samsung_fhd_vid.xml
}


FILE FREEFORM = 8EC6EB8E-3082-48A5-BE97-42542808A5DC {
    SECTION UI = "Panel_oplus20241_s6e8fc1fe_samsung_fhd_vid.xml"
    SECTION RAW = RawFiles/Panel_oplus20241_s6e8fc1fe_samsung_fhd_vid.xml
}


FILE FREEFORM = 7D0A5CC2-895C-4BA1-A208-26F1B1088E1F {
    SECTION UI = "Panel_oplus20241_am643_samsung_fhd_vid.xml"
    SECTION RAW = RawFiles/Panel_oplus20241_am643_samsung_fhd_vid.xml
}


FILE FREEFORM = E16FA550-6FCC-4645-A758-5F6E38630071 {
    SECTION UI = "Panel_boe_ili9881h_hd_vid.xml"
    SECTION RAW = RawFiles/Panel_boe_ili9881h_hd_vid.xml
}


FILE FREEFORM = B0DB2C7D-70D8-4F1E-A90F-32CC3B4698B7 {
    SECTION UI = "Panel_boe_ili9881h_hd_90hz_vid.xml"
    SECTION RAW = RawFiles/Panel_boe_ili9881h_hd_90hz_vid.xml
}


FILE FREEFORM = 62687A82-24C0-48DA-8F35-C29F2E42A512 {
    SECTION UI = "Panel_hlt_ili9881h_hd_90hz_vid.xml"
    SECTION RAW = RawFiles/Panel_hlt_ili9881h_hd_90hz_vid.xml
}


FILE FREEFORM = 0F85E1C9-6246-4D73-8F66-C0D05EA12BD0 {
    SECTION UI = "Panel_tm_hx83112a_hd_90hz_vid.xml"
    SECTION RAW = RawFiles/Panel_tm_hx83112a_hd_90hz_vid.xml
}


FILE FREEFORM = 66CE27C5-84D0-4F65-A4BF-16027AD2FBC3 {
    SECTION UI = "Panel_liansi_ili9881h_hd_vid.xml"
    SECTION RAW = RawFiles/Panel_liansi_ili9881h_hd_vid.xml
}


FILE FREEFORM = CCEE056F-CECB-43E9-ABA2-EB0CFA4BE4CB {
    SECTION UI = "Panel_inx_nt36525b_hd_vid.xml"
    SECTION RAW = RawFiles/Panel_inx_nt36525b_hd_vid.xml
}


FILE FREEFORM = 2151FA08-9E40-405C-86DE-16539838710A {
    SECTION UI = "Panel_hlt_nt36525b_hd_vid.xml"
    SECTION RAW = RawFiles/Panel_hlt_nt36525b_hd_vid.xml
}


FILE FREEFORM = E181EC3D-CD03-4BB8-9BDC-2901F274A033 {
    SECTION UI = "Panel_cdot_ili9882n_hd_vid.xml"
    SECTION RAW = RawFiles/Panel_cdot_ili9882n_hd_vid.xml
}


FILE FREEFORM = 174B9B2E-108D-4450-B579-454C4440A78A {
    SECTION UI = "Panel_truly_ili9882n_hd_vid.xml"
    SECTION RAW = RawFiles/Panel_truly_ili9882n_hd_vid.xml
}


FILE FREEFORM = C9A17FD2-19F3-48A5-BF75-A5DDBFD34EA5 {
    SECTION UI = "Panel_sim_vid_panel.xml"
    SECTION RAW = RawFiles/Panel_sim_vid_panel.xml
}


FILE FREEFORM = 569FA21D-AF57-4DD0-9364-836B703FA854 {
    SECTION UI = "Panel_ili9881h_boe_fhd_video.xml"
    SECTION RAW = RawFiles/Panel_ili9881h_boe_fhd_video.xml
}


FILE FREEFORM = 61119338-DF2F-4975-8627-1C2E9CBB9039 {
    SECTION UI = "Panel_nt36525b_inx_fhd_video.xml"
    SECTION RAW = RawFiles/Panel_nt36525b_inx_fhd_video.xml
}


FILE FREEFORM = ADEAB740-7371-43C9-98B5-CCC3F947D2DD {
    SECTION UI = "Panel_ili9881h_90hz_boe_fhd_video.xml"
    SECTION RAW = RawFiles/Panel_ili9881h_90hz_boe_fhd_video.xml
}


FILE FREEFORM = C737910E-9415-46FA-8907-3FA9C8E2AAA5 {
    SECTION UI = "Panel_nt36525b_90hz_inx_fhd_video.xml"
    SECTION RAW = RawFiles/Panel_nt36525b_90hz_inx_fhd_video.xml
}


FILE FREEFORM = A2652206-9577-4FE8-B3A0-489AF6DE0FED {
    SECTION UI = "Panel_ili9881h_90hz_hlt_fhd_video.xml"
    SECTION RAW = RawFiles/Panel_ili9881h_90hz_hlt_fhd_video.xml
}


FILE FREEFORM = 32D2A295-2EEB-41B0-8429-5AAB136E9AE9 {
    SECTION UI = "Panel_ili9882n_90hz_txd_fhd_video.xml"
    SECTION RAW = RawFiles/Panel_ili9882n_90hz_txd_fhd_video.xml
}


FILE FREEFORM = A2CE36BE-C9AA-447F-9DE5-30676A7608DE {
    SECTION UI = "Panel_ili9882n_90hz_boe_fhd_video.xml"
    SECTION RAW = RawFiles/Panel_ili9882n_90hz_boe_fhd_video.xml
}


FILE FREEFORM = BBC6C787-C00F-423A-9324-A7F8F5A81A48 {
    SECTION UI = "Panel_ili9882n_90hz_inx_fhd_video.xml"
    SECTION RAW = RawFiles/Panel_ili9882n_90hz_inx_fhd_video.xml
}


FILE FREEFORM = CE2FD52F-ACD0-4CA3-926C-4752496E5315 {
    SECTION UI = "Panel_oplus20211_s6e8fc1_samsung_fhd_vid.xml"
    SECTION RAW = RawFiles/Panel_oplus20211_s6e8fc1_samsung_fhd_vid.xml
}


FILE FREEFORM = 3E5584ED-05D4-4267-9048-0D47F76F4248 {
    SECTION UI = "battery_symbol_Soc10.bmp"
    SECTION RAW = RawFiles/battery_symbol_Soc10.bmp
}


FILE FREEFORM = 4753E815-DDD8-402D-BF69-9B8C4EB7573E {
    SECTION UI = "battery_symbol_NoBattery.bmp"
    SECTION RAW = RawFiles/battery_symbol_NoBattery.bmp
}


FILE FREEFORM = 03DED53E-BECD-428F-9F79-5ABA64C58445 {
    SECTION UI = "battery_symbol_Nocharger.bmp"
    SECTION RAW = RawFiles/battery_symbol_Nocharger.bmp
}


FILE FREEFORM = 8B86CD38-C772-4FCF-85AA-345B2B3C1AB4 {
    SECTION UI = "battery_symbol_LowBatteryCharging.bmp"
    SECTION RAW = RawFiles/battery_symbol_LowBatteryCharging.bmp
}


FILE FREEFORM = 3FD97907-93F1-4349-AF3C-3B68B0A5E626 {
    SECTION UI = "battery_symbol_LowBattery.bmp"
    SECTION RAW = RawFiles/battery_symbol_LowBattery.bmp
}


FILE FREEFORM = B0F8D1BE-5353-4812-B1F6-07E7768204CC {
    SECTION UI = "battery_symbol_DebugBoot.bmp"
    SECTION RAW = RawFiles/battery_symbol_DebugBoot.bmp
}


FILE FREEFORM = F9E8F683-E065-4E09-B4F9-0230D7CECD08 {
    SECTION UI = "battery_symbol_DebugStay.bmp"
    SECTION RAW = RawFiles/battery_symbol_DebugStay.bmp
}


FILE FREEFORM = E2EA5A4F-98BD-4203-AB49-399505DDFB7D {
    SECTION UI = "tsens_thermal_symbol.bmp"
    SECTION RAW = RawFiles/tsens_thermal_symbol.bmp
}


FILE FREEFORM = C72FB1A9-5527-4E13-BAC4-F671D0330145 {
    SECTION UI = "tsens_thermal_err_symbol.bmp"
    SECTION RAW = RawFiles/tsens_thermal_err_symbol.bmp
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}


FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
    SECTION UI = "QcomChargerCfg.cfg"
    SECTION RAW = RawFiles/QcomChargerCfg.cfg
}


FILE FREEFORM = F780C779-DD7C-47CD-BD1A-5EB414C51704 {
    SECTION UI = "BATTERY.PROVISION"
    SECTION RAW = RawFiles/BATTERY.PROVISION
}


FILE FREEFORM = 44E7BB0B-12EA-43E0-A16A-7FAD77131E21 {
    SECTION UI = "verifyboot.bmp"
    SECTION RAW = RawFiles/verifyboot.bmp
}

