[PcdsFixedAtBuild.common]
gAndromedaPkgTokenSpaceGuid.PcdMipiFrameBufferWidth|1080
gAndromedaPkgTokenSpaceGuid.PcdMipiFrameBufferHeight|2400

# Smbios Info
gAndromedaPkgTokenSpaceGuid.PcdSmbiosSystemBrand|"Samsung"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosSystemModel|"Galaxy A52s 5G"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosSystemRetailModel|"a52sxq"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosSystemRetailSku|"SM-A528B/N"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosProcessorRetailModel|"SM7325"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosProcessorModel|"Snapdragon (TM) 778G 5G @ 2.40 GHz"

gAndromedaPkgTokenSpaceGuid.PcdABLProduct|"a52sxq"

# Display Caller
#gAndromedaPkgTokenSpaceGuid.PcdDisplayCallerExitDisableDisplay|FALSE
#gAndromedaPkgTokenSpaceGuid.PcdDisplayCallerStallBeforeEnable|0

# Storage
gAndromedaPkgTokenSpaceGuid.PcdStorageHasUFS3|0
