[PcdsFixedAtBuild.common]
gAndromedaPkgTokenSpaceGuid.PcdMipiFrameBufferWidth|720
gAndromedaPkgTokenSpaceGuid.PcdMipiFrameBufferHeight|1600

# Smbios Info
gAndromedaPkgTokenSpaceGuid.PcdSmbiosSystemBrand|"OPPO"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosSystemModel|"A32"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosSystemRetailModel|"PDVM00"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosSystemRetailSku|"SM-A528B/N"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosProcessorRetailModel|"SM4250"
gAndromedaPkgTokenSpaceGuid.PcdSmbiosProcessorModel|"Snapdragon (TM) 460 Mobile Platform @ 1.80 GHz"

gAndromedaPkgTokenSpaceGuid.PcdABLProduct|"A32"

# Display Caller
#gAndromedaPkgTokenSpaceGuid.PcdDisplayCallerExitDisableDisplay|FALSE
#gAndromedaPkgTokenSpaceGuid.PcdDisplayCallerStallBeforeEnable|0

# Storage
gAndromedaPkgTokenSpaceGuid.PcdStorageHasUFS3|0
